language: php

php:
  - 7.0

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

branches:
  only:
    - master

before_script:
  - mysql -e 'create database lavarel;'
  - cp .env.ci.example .env  #copy over CI environment configuration
  - php artisan key:generate
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer update
  - chmod -R 777 storage/
  - php artisan migrate
  - php artisan db:seed
  - php -S localhost:8000 -t public &
  - sleep 5 # give artisan serve some time to start

script:
  - php tests/CreatesApplication.php


after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*